[workspace]
resolver = "3"
members = ["modules/common", "modules/quote-server", "modules/quote-client"]

[workspace.dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
rkyv = "0.8"
zerocopy = "0.8.31"

