name: Package validation
on:
  push:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cargo-audit:
    name: Cargo packages audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Cargo
        uses: ./.github/actions/setup-cargo
      - name: Setup stable Rust version
        run: |
          rustup toolchain install stable --profile minimal
      - name: Install Cargo audit
        run: |
          if ! which cargo-audit; then
            cargo install cargo-audit
          fi
      - name: Validate packages
        run: |
          cargo audit      
