name: Easy release
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Semantic release type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.RELEASE_AUTOMATION_PAT }}
      - name: Easy merge
        id: easy-merge
        uses: arthurhovhannisyan31/easy-merge-action@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_AUTOMATION_PAT }}
        with:
          source_branch: "develop"
          target_branch: "main"
          release_type: ${{ inputs.release_type }}
      - name: Easy release
        id: easy-release
        uses: arthurhovhannisyan31/easy-release-action@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_AUTOMATION_PAT }}
        with:
          branch: "main"
      - name: Log outputs
        run: |
          echo Released tag: ${{ steps.easy-merge.outputs.release_tag }}
          echo Release URL: ${{ steps.easy-release.outputs.release_url }}
